# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especieNOMBRECOMUN', models.CharField(max_length=250, verbose_name='Nombre')),
                ('especieNOMBRECIENTIFICO', models.CharField(max_length=250, verbose_name='Nombre Cientifico')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='EspeciesFamilias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especieFamiliaTITULO', models.CharField(max_length=250, verbose_name='Especie Familia Titulo')),
            ],
            options={
                'verbose_name': 'Familia Especie',
                'verbose_name_plural': 'Familia Especie',
            },
        ),
        migrations.AddField(
            model_name='especies',
            name='especieFamiliaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especies.EspeciesFamilias', verbose_name='EspecieFamilia'),
        ),
    ]
