# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avistamientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avistamientoLATITUD', models.CharField(max_length=250, verbose_name='Latitud')),
                ('avistamientoLONGITUD', models.CharField(max_length=250, verbose_name='Longitud')),
                ('avistamientoOBSERVACIONES', models.CharField(max_length=250, verbose_name='Observaciones')),
                ('avistamientoAUTOR', models.CharField(max_length=250, verbose_name='Nombre de Autor')),
                ('especieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especies.Especies', verbose_name='Especie')),
                ('lugarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Lugares', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Avistamiento',
                'verbose_name_plural': 'Avistamientos',
            },
        ),
    ]
