# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentoCODIGO', models.CharField(max_length=250, verbose_name='Codigo')),
                ('departamentoNOMBRE', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarTITULO', models.CharField(max_length=250, verbose_name='Codigo')),
                ('lugarALIAS', models.CharField(max_length=250, verbose_name='Nombre')),
                ('departamentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Departamentos', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisCODIGO', models.CharField(max_length=250, verbose_name='Codigo')),
                ('paisNOMBRE', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='paisID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Paises', verbose_name='Pais'),
        ),
    ]
